const PUBLIC_DEFAULTS = {
  DEFAULT_DROPBOX_APP_KEY: "uwxv4ofkrmc4zzf",
  DEFAULT_ONEDRIVE_CLIENT_ID: "3729fc1c-0af2-4bec-9376-d7ac4f0ff806",
  DEFAULT_ONEDRIVE_AUTHORITY: "https://login.microsoftonline.com/common",
};

function getBuildDefaults(env = process.env) {
  return {
    DEFAULT_DROPBOX_APP_KEY:
      env.DROPBOX_APP_KEY || PUBLIC_DEFAULTS.DEFAULT_DROPBOX_APP_KEY,
    DEFAULT_ONEDRIVE_CLIENT_ID:
      env.ONEDRIVE_CLIENT_ID || PUBLIC_DEFAULTS.DEFAULT_ONEDRIVE_CLIENT_ID,
    DEFAULT_ONEDRIVE_AUTHORITY:
      env.ONEDRIVE_AUTHORITY || PUBLIC_DEFAULTS.DEFAULT_ONEDRIVE_AUTHORITY,
    DEFAULT_REMOTELYSAVE_WEBSITE: env.REMOTELYSAVE_WEBSITE || "",
    DEFAULT_REMOTELYSAVE_CLIENT_ID: env.REMOTELYSAVE_CLIENT_ID || "",
    DEFAULT_GOOGLEDRIVE_CLIENT_ID: env.GOOGLEDRIVE_CLIENT_ID || "",
    DEFAULT_GOOGLEDRIVE_CLIENT_SECRET: env.GOOGLEDRIVE_CLIENT_SECRET || "",
    DEFAULT_BOX_CLIENT_ID: env.BOX_CLIENT_ID || "",
    DEFAULT_BOX_CLIENT_SECRET: env.BOX_CLIENT_SECRET || "",
    DEFAULT_PCLOUD_CLIENT_ID: env.PCLOUD_CLIENT_ID || "",
    DEFAULT_PCLOUD_CLIENT_SECRET: env.PCLOUD_CLIENT_SECRET || "",
    DEFAULT_YANDEXDISK_CLIENT_ID: env.YANDEXDISK_CLIENT_ID || "",
    DEFAULT_YANDEXDISK_CLIENT_SECRET: env.YANDEXDISK_CLIENT_SECRET || "",
    DEFAULT_KOOFR_CLIENT_ID: env.KOOFR_CLIENT_ID || "",
    DEFAULT_KOOFR_CLIENT_SECRET: env.KOOFR_CLIENT_SECRET || "",
  };
}

module.exports = {
  PUBLIC_DEFAULTS,
  getBuildDefaults,
};
